import { Injectable } from '@nestjs/common';
import { IntakeListDetails } from 'src/common/types/intakeListDetails.types';
import { Logger } from '@nestjs/common';
import { getEmailKind } from 'src/email/email.helper';

@Injectable()
export class LlmService {

     private readonly logger = new Logger(LlmService.name);



    /**
   * Builds a formal appointment reminder email using an LLM.
   */

    async buildReminderEmail(appt:IntakeListDetails) : Promise<string>{
 
     this.logger.log(
      `Building reminder email for appointmentId=${appt.appointment_id}, patient=${appt.first_name} ${appt.last_name}`,
    );

    const kind = getEmailKind(appt);
    
    const start = new Date(appt.appointment_time);
    const date = start.toLocaleDateString();
    const time = start.toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
    });
   
     // choose prompt based on kind
  const { systemPrompt, userPrompt } = this.buildPrompts(kind, appt, date, time);

    const apiKey = process.env.OPENAI_API_KEY;
    console.log("API key=",apiKey);
    
    if (!apiKey) {
      // Fallback to a non-LLM email if key is missing
      this.logger.warn(
        `OPENAI_API_KEY missing. Falling back to static email template for appointmentId=${appt.appointment_id}`,
      );
      return this.buildFakeEmail(kind, appt, date, time);
    }
    this.logger.debug(
      `Calling OpenAI for appointmentId=${appt.appointment_id} (model=gpt-4.1-mini)`,
    );
    try{
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-mini', 
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
      }),
    });

    const data = await response.json();
    
    const content =
      data?.choices?.[0]?.message?.content ??
      this.buildFakeEmail(kind,appt, date, time);

    return content;
 }
catch (error) {
      this.logger.error(
        `Error while calling OpenAI for appointmentId=${appt.appointment_id}`,
        error instanceof Error ? error.stack : undefined,
      );

      return this.buildFakeEmail(kind,appt, date, time);
    }

    }

    private buildPrompts(
  kind: "READY_REMINDER" | "INTAKE_MISSING" | "INSURANCE_ISSUE",
  appt: IntakeListDetails,
  date: string,
  time: string,
) {
  const systemPrompt = `
You are an assistant for a healthcare clinic.
Write a short, professional, and polite patient email.
Use a formal but friendly tone.
Do NOT mention AI or that this was generated by a model.
Keep it concise and action-oriented.
`.trim();

  if (kind === "READY_REMINDER") {
    return {
      systemPrompt,
      userPrompt: `
Patient first name: ${appt.first_name}
Appointment: ${date} at ${time}
Clinic name: Beam Health

Write a reminder email that:
- Confirms the appointment date/time
- Asks them to contact the clinic if they need to reschedule
- Ends with "Best regards, Beam Health"
`.trim(),
    };
  }

  if (kind === "INTAKE_MISSING") {
    return {
      systemPrompt,
      userPrompt: `
Patient first name: ${appt.first_name}
Appointment: ${date} at ${time}
Clinic name: Beam Health
Intake status: ${appt.intake_status}

Write an email that:
- Reminds them of the appointment date/time
- Explains that required intake forms are still missing
- Asks them to complete forms before the visit (no links; just mention "patient portal" / "forms sent previously")
- Offers help if they have trouble accessing forms
- Ends with "Best regards, Beam Health"
`.trim(),
    };
  }

  // INSURANCE_ISSUE
  return {
    systemPrompt,
    userPrompt: `
Patient first name: ${appt.first_name}
Appointment: ${date} at ${time}
Clinic name: Beam Health
Eligibility status: ${appt.eligibility_status}

Write an email that:
- Reminds them of the appointment date/time
- Notes there appears to be an insurance eligibility issue that may affect coverage
- Asks them to contact the clinic to confirm insurance details before the visit
- Reassures them we can help resolve it
- Ends with "Best regards, Beam Health"
`.trim(),
  };
}


    private buildFakeEmail(
  kind: "READY_REMINDER" | "INTAKE_MISSING" | "INSURANCE_ISSUE",
  appt: IntakeListDetails,
  date: string,
  time: string,
): string {
  if (kind === "INTAKE_MISSING") {
    return `Dear ${appt.first_name},

This is a reminder of your upcoming appointment on ${date} at ${time} with Beam Health.

Our records show that some required intake forms are still missing. Please complete the forms in your patient portal before your visit. If you have trouble accessing them, reply to this email or contact the clinic and we’ll help.

Best regards,
Beam Health`;
  }

  if (kind === "INSURANCE_ISSUE") {
    return `Dear ${appt.first_name},

This is a reminder of your upcoming appointment on ${date} at ${time} with Beam Health.

We also noticed a potential insurance eligibility issue (${appt.eligibility_status}). To avoid delays at check-in, please contact the clinic to confirm your insurance details before your visit. We’re happy to help resolve this.

Best regards,
Beam Health`;
  }

  // READY_REMINDER
  return `Dear ${appt.first_name},

This is a reminder of your upcoming appointment scheduled for ${date} at ${time} with Beam Health.

If you need to cancel or reschedule this appointment, please contact the clinic at your earliest convenience.

Best regards,
Beam Health`;
}



}
